---
name: snmpd build
description: Build snmpd

runs:
  using: "composite"
  steps:
    - run: |
        echo ::group::Download the source
        sudo apt-get install snmpd
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Extract the contents
        sudo apt-get install snmp
        echo ::endgroup::
      shell: bash

    # - run: |
    #     echo ::group::Confirm the snmp walk works
    #     snmpwalk -Os -c public -v 1 localhost
    #     echo ::endgroup::
    #   shell: bash
