name: netsnmp build
description: Build netsnmp

inputs:
  version:
    description: the netsnmp version
    required: true
    default: 5.9.1

runs:

  using: "composite"
  steps:
  
    - run: wget http://sourceforge.net/projects/net-snmp/files/net-snmp/${{ inputs.version }}/net-snmp-${{ inputs.version }}.tar.gz
      shell: bash

    - run: tar -xvf net-snmp-${{ inputs.version }}.tar.gz
      shell: bash

    - run: sudo apt-get install libperl-dev
      shell: bash

    - run: ./configure --with-python-modules --libdir=/usr/lib64 --enable-shared
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}

    - run: make
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}

    - run: sudo make install
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}

    - run: snmpget --version
      shell: bash

    - run: python3 setup.py build
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}/python

    - name: Ensure setuptools is installed for sudo
      run: sudo pip3 install setuptools
      shell: bash

    - run: sudo python3 setup.py install
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}/python
    
    - run: python3 -c 'import netsnmp'
      shell: bash

