name: netsnmp build
description: Build netsnmp

inputs:
  version:
    description: the netsnmp version
    required: true
    default: 5.9.1

runs:

  using: "composite"
  steps:
  
    - name: Download the netsnmp source
      run: wget http://sourceforge.net/projects/net-snmp/files/net-snmp/${{ inputs.version }}/net-snmp-${{ inputs.version }}.tar.gz
      shell: bash

    - name: Extract the contents
      run: tar -xvf net-snmp-${{ inputs.version }}.tar.gz
      shell: bash

    - name: Install dependancies
      run: sudo apt-get install libperl-dev
      shell: bash

    - name: Configure the source
      run: ./configure --with-python-modules --libdir=/usr/lib64 --enable-shared
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}

    - name: Make snmp
      run: make
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}

    - name: Install netsnmp
      run: sudo make install
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}

    - name: Confrim version 
      run: snmpget --version
      shell: bash

    - name: Build the python bindings
      run: python3 setup.py build
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}/python

    - name: Ensure setuptools is installed for sudo
      run: sudo pip3.8 install setuptools
      shell: bash

    - name: Install the python bindings
      run: sudo python3.8 setup.py install
      shell: bash
      working-directory: net-snmp-${{ inputs.version }}/python
    
    - name: Confim python binding available
      run: python3 -c 'import netsnmp'
      shell: bash

