- hosts: all
  gather_facts: False
  tasks:
  - name: Retreive several individual OIDs
    ansible.snmp.get:
      oids:
      - "SNMPv2-MIB::sysContact.0"
      - "SNMPv2-MIB::sysLocation.0"
      numeric: False
      long_names: True

  - name: Set several individual OIDs
    ansible.snmp.set:
      oids:
      - oid: "SNMPv2-MIB::sysContact"
        iid: '0'
        value: "Brad Thornton @ {{ ts }}"
      - oid: "SNMPv2-MIB::sysLocation"
        iid: '0'
        value: "Basement @ {{ ts }}"
    vars:
      ts: "{{ lookup('pipe', 'date -u +\"%Y-%m-%dT%H:%M:%SZ\"') }}"

  - name: Retreive several changed OIDs
    ansible.snmp.get:
      oids:
      - "SNMPv2-MIB::sysContact.0"
      - "SNMPv2-MIB::sysLocation.0"

  - name: Retrieve an entire table, cell by cell
    ansible.snmp.walk:
      oids:
      - IF-MIB::ifTable
  - name: Retrieve an entire table, row by row
    ansible.snmp.walk:
      oids:
      - IF-MIB::ifIndex
      - IF-MIB::ifDescr
      - IF-MIB::ifType
      - IF-MIB::ifMtu
      - IF-MIB::ifSpeed
      - IF-MIB::ifPhysAddress
      - IF-MIB::ifAdminStatus
      - IF-MIB::ifOperStatus
      - IF-MIB::ifLastChange
      - IF-MIB::ifInOctets
      - IF-MIB::ifInUcastPkts
      - IF-MIB::ifInDiscards
      - IF-MIB::ifInErrors
      - IF-MIB::ifInUnknownProtos
      - IF-MIB::ifOutOctets
      - IF-MIB::ifOutUcastPkts
      - IF-MIB::ifOutDiscards
      - IF-MIB::ifOutErrors
      - IF-MIB::ifSpecific
  - name: Retrieve the route table row by row
    ansible.snmp.walk:
      oids:
      - RFC1213-MIB::ipRouteDest
      - RFC1213-MIB::ipRouteIfIndex
      - RFC1213-MIB::ipRouteMetric1
      - RFC1213-MIB::ipRouteMetric2
      - RFC1213-MIB::ipRouteMetric3
      - RFC1213-MIB::ipRouteMetric4
      - RFC1213-MIB::ipRouteNextHop
      - RFC1213-MIB::ipRouteType
      - RFC1213-MIB::ipRouteProto
      - RFC1213-MIB::ipRouteAge
      - RFC1213-MIB::ipRouteMask
      - RFC1213-MIB::ipRouteMetric5
      - RFC1213-MIB::ipRouteInfo

  
