name: Install deps
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install netsnmp
        run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp
      - name: Install navigator
        run: pip3 install ansible-navigator ansible-core
      - name: Run
        run: ansible-navigator run $PB_PATH/site.yaml --ee false
        env:
          pb_path: ${{ github.workspace }}/playbooks
          