name: Install deps
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install netsnmp
        run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp
      - name: Install navigator
        run: pip3 install ansible-navigator ansible-core
          