name: Install deps
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Collection basics
        run: pip3 install pyyaml yq
      - name: Extract collection namespace
        id: collection_namespace
        run: |
          echo "::set-output name=value::$(cat galaxy.yml | yq .namespace)"
      - name: Extract collection name
        id: collection_name
        run: |
          echo "::set-output name=value::$(cat galaxy.yml | yq .name)"
      
      - run: echo ::notice title=Collection namespace::${{ steps.collection_namespace.outputs.value }}
      - run: echo ::notice title=Collection name::${{ steps.collection_name.outputs.value }}


      # - run: echo "Collection name set to '${{ steps.collection_name.outputs.value }}'"

      # Collection dependancies
      - name: Install netsnmp
        run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp
      - name: Install navigator
        run: pip3 install ansible-navigator ansible-core
      
      # Move to collection path
      - name: Make collection namespace directory
        run: mkdir -p /usr/share/ansible/collections/ansible_collections/${{ steps.collection_namespace.outputs.value }}
      - run: echo $GITHUB_WORKSPACE
      - name: Link the collection as colleciton name
        run: ln -s $GITHUB_WORKSPACE /usr/share/ansible/collections/ansible_collections/${{ steps.collection_namespace.outputs.value }}/${{ steps.collection_name.outputs.value }}
      
      - run: ls /usr/share/ansible/collections/ansible_collections/${{ steps.collection_namespace.outputs.value }}/${{ steps.collection_name.outputs.value }}
      - name: Run
        run: ansible-navigator run playbooks/site.yaml --ee false --mode stdout
      
          