name: Collection integration tests
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Github action python requirements
        run: pip3 install yq

      - name: Extract collection namespace
        id: collection_namespace
        run: |
          echo '::set-output name=value::$(cat galaxy.yml | yq .namespace)'
      - name: Extract collection name
        id: collection_name
        run: |
          echo '::set-output name=value::$(cat galaxy.yml | yq .name)'
      
      - run: echo ::notice title=Collection namespace::${{ steps.collection_namespace.outputs.value }}
      - run: echo ::notice title=Collection name::${{ steps.collection_name.outputs.value }}



      # Collection system dependancies
      - name: Install netsnmp
        run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp
      
      # Collection test
      - name: Install navigator
        run: pip3 install -r test-requirements.txt
      
      # Install the collection
      - run: ansible-galaxy collection install . -p /usr/share/ansible/collections/ansible_collections

      
      - name: Run
        run: ansible-navigator run tests/integration/run.yml --ee false --mode stdout -e collection_namespace=${{ steps.collection_namespace.outputs.value }} -e collection_name=${{ steps.collection_name.outputs.value }}
      
          