name: Collection integration tests
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Github action python requirements
        run: pip3 install yq

      - name: Extract collection namespace
        id: collection_namespace
        run: |
          echo "::set-output name=value::$(cat galaxy.yml | yq -r .namespace)"
      - name: Extract collection name
        id: collection_name
        run: |
          echo "::set-output name=value::$(cat galaxy.yml | yq -r .name)"
      
      - run: echo ::notice title=Collection namespace::${{ steps.collection_namespace.outputs.value }}
      - run: echo ::notice title=Collection name::${{ steps.collection_name.outputs.value }}

      - run: wget http://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.1/net-snmp-5.9.1.tar.gz
      - run: tar -xvf net-snmp-5.9.1.tar.gz
      - run: sudo apt-get install libperl-dev
      - run: ./configure --with-python-modules --libdir=/usr/lib64 --enable-shared
        working-directory: net-snmp-5.9.1
      - run: make
        working-directory: net-snmp-5.9.1
      - run: sudo make install
        working-directory: net-snmp-5.9.1
      - run: snmpget --version
      - run: python setup.by build
        working-directory: net-snmp-5.9.1/python
      - run: python setup.py install
        working-directory: net-snmp-5.9.1/python






      # # Collection system dependancies
      # - name: Install netsnmp
      #   run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp

      # - name: venv
      #   run: python -m venv venv --system-site-packages
      
      # - run: source venv/bin/activate

      
      # Collection test
      - name: Install navigator
        run: pip3 install -r test-requirements.txt
      
      # Install the collection
      - run: ansible-galaxy collection install . -p /usr/share/ansible/collections/ansible_collections

      
      - name: Run
        run: ansible-navigator 
        env:
          ANSIBLE_VERBOSITY: 4
          ANSIBLE_NAVIGATOR_APP: run
          ANSIBLE_NAVIGATOR_MODE: stdout
          ANSIBLE_NAVIGATOR_PLAYBOOK: tests/integration/integration_runner.yaml
          ANSIBLE_NAVIGATOR_INVENTORIES: tests/integration/integration_inventory.yaml
          ANSIBLE_NAVIGATOR_EXECUTION_ENVIRONMENT: False
          COLLECTION_NAMESPACE:  ${{ steps.collection_namespace.outputs.value }}
          COLLECTION_NAME: ${{ steps.collection_name.outputs.value }}
          INTEGRATION_TESTS_PATTERN: "*"

          