name: Install deps
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Collection basics
        run: pip3 install pyyaml
      - name: Extract collection namespace
        id: collection_namespace
        run: |
          echo "::set-output name=value::$(python -c 'import yaml, sys; obj=yaml.safe_load(sys.stdin); print(obj[\"namespace\"])' < galaxy.yml)"
      - name: Extract collection name
        id: collection_name
        run: |
          echo "::set-output name=value::$(python -c 'import yaml, sys; obj=yaml.safe_load(sys.stdin); print(obj[\"name\"])' < galaxy.yml)"
      
      - run: echo "${{ steps.collection_namespace.outputs.value }}"
      - run: echo "${{ steps.collection_name.outputs.value }}"
      # Collection dependancies
      - name: Install netsnmp
        run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp
      - name: Install navigator
        run: pip3 install ansible-navigator ansible-core
      
      # Move to collection path
      - name: Make collection directory
        run: mkdir -p /usr/share/ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
      - name: Link
        run: ln -s $GITHUB_WORKSPACE /usr/share/ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
      - name: Run
        run: ansible-navigator run playbooks/site.yaml --ee false --mode stdout
      
          