name: Collection integration tests
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Download and build netsnmp
        uses: ./.github/actions/netsnmp
        with:
          netsnmp-version: 5.9.1
          python-version: ${{ matrix.python-version }}
      
      - name: Prepare the collection
        id: prepare_collection
        uses: ./.github/actions/ansible_collection

      # Collection test
      - name: Install navigator
        run: pip3 install -r test-requirements.txt
      

      - name: Run
        run: ansible-navigator 
        env:
          ANSIBLE_VERBOSITY: 4
          ANSIBLE_NAVIGATOR_APP: run
          ANSIBLE_NAVIGATOR_MODE: stdout
          ANSIBLE_NAVIGATOR_PLAYBOOK: tests/integration/integration_runner.yaml
          ANSIBLE_NAVIGATOR_INVENTORIES: tests/integration/integration_inventory.yaml
          ANSIBLE_NAVIGATOR_EXECUTION_ENVIRONMENT: False
          COLLECTION_NAMESPACE:  ${{ steps.prepare_collection.outputs.collection_namespace }}
          COLLECTION_NAME: ${{ steps.prepare_collection.outputs.collection_name }}
          INTEGRATION_TESTS_PATTERN: "*"

          