name: Install deps
on: [push]
jobs:
  deps:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ansible.snmp
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install netsnmp
        run: sudo apt-get install -y snmpd snmp libsnmp-dev python-netsnmp
      - name: Install navigator
        run: pip3 install ansible-navigator ansible-core
      - name: Link
        run: ln -s ansible.snmp /usr/share/ansible/collections/ansible_collections/ansible/snmp
      - name: Run
        run: ansible-navigator run playbooks/site.yaml --ee false --mode stdout
      
          